version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase-if-necessary"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      synchronized-actions:
        applies-to: "version-updates"
        patterns:
          - "*"
      synchronized-actions-security:
        applies-to: "security-updates"
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"
